   services:
     minio:
       image: minio/minio
       ports:
         - "9300:9000"
       volumes:
         - minio_data:/data
       environment:
         MINIO_ACCESS_KEY: admin
         MINIO_SECRET_KEY: Voipera
       command: server /data

   volumes:
     minio_data:
